server:
  servlet:
    context-path: /rest
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: 
  application:
    name: userApi
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/UserApi
    username: root
    password: pass123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  cache:
    cache-names: getById
    caffeine:
      spec: maximumSize=50, expireAfterAccess=1h